### ISSUE TITLE
Is ScaledASM transfer function correct for `R > 1`?

### ISSUE THREAD

**Issue by Islam0mar** [syoshida1983/AngularSpectrumMethod.jl#8]
``` julia
H = @. exp(2π*im*z*√(1/λ^2 - (f[1]/Δy)^2 - (f[2]'/Δx)^2 + 0im)) # transfer function R ≤ 1
H = @. exp(2π*im*z*√(1/λ^2 - (f[1]/Δy*S)^2 - (f[2]'/Δx*S)^2 + 0im)) # transfer function R > 1
``` 

Otherwise `H` isn't taking the used frequencies.

**Comment by syoshida1983** [comment]
Scaled ASM adjusts the scale by changing the sampling pitch in the source or destination plane. The sampling pitch in the spatial frequency domain does not change regardless of the value of _R_. Please refer to the figure below (cited from Ref. 1).

![ScaledASM](https://github.com/syoshida1983/AngularSpectrumMethod.jl/assets/98638350/7d009556-2cc6-490b-9feb-fcd919795b1c)

> 1. [Tomoyoshi Shimobaba, Kyoji Matsushima, Takashi Kakue, Nobuyuki Masuda, and Tomoyoshi Ito, "Scaled angular spectrum method," Opt. Lett. 37, 4128-4130 (2012)](https://doi.org/10.1364/OL.37.004128)

**Comment by Islam0mar** [comment]
As far as I understand $\Delta_f(R \leq 1)  = \frac{1}{2N\Delta_1}$, while $\Delta_f(R > 1)  = \frac{1}{2N\Delta_2}$ . From paper first line after equation 3 and equation 6 respectively.

Tried to visualize the result when the observation screen is at the same distance:
- Old H(z = 100mm):
  ![without](https://github.com/syoshida1983/AngularSpectrumMethod.jl/assets/16095581/ef16d24a-9cc3-44f7-8f0b-e1a520f7088b)
- New H(z = 100mm):
 ![with](https://github.com/syoshida1983/AngularSpectrumMethod.jl/assets/16095581/e7962226-a2eb-469e-9943-afc864ce77d7)
- ASM no scaling(z = 100mm):
 ![no](https://github.com/syoshida1983/AngularSpectrumMethod.jl/assets/16095581/481b0047-7d5a-4177-a012-008ef0a19faf)

For the same distance and $R > 1$ doesn't give the same pattern obtained from no scaling. 

Also [cwo++](https://cwolibrary.sourceforge.net/) code:
```C++
                        CWO *mp=(CWO *)new CWO;
			mp->SamplingMapScaleOnly(Nx,Ny,R,1.0f);	
			cwoFloat2 *p_map=(cwoFloat2*)mp->GetBuffer();
			__NUFFT_T1(a,p_map,1,2);
						
			delete mp;//important ! avoiding meory leak

=========>  SetPitch(GetDstPx(),GetDstPy()); // This line
			//SetOffset(GetDstOx()-GetSrcOx(),-(GetDstOy()-GetSrcOy()));
			__AngularProp(a,CWO_PROP_MUL_CENTER);
```

**Comment by syoshida1983** [comment]
Thank you for detailed information. As you indicated, it was a misreading of the paper on my part. A fixed version, v.0.2.2, has been released.

**Comment by Islam0mar** [comment]
Thanks a lot for your package.
